version: '3.8'

services:

  backend:
    build:
      context: .
    ports:
      - '8081:8081'
    depends_on:
      - db

  db:
    image: mongo
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=mongo
