version: '3.8'

services:

  backend:
    build:
      context: .
    restart: unless-stopped
    ports:
      - '8081:8081'
    depends_on:
      - db

  db:
    image: mongo
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - db:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=mongo

volumes:
  db: